[ja]
  title = "ゲームとか学修備忘録"
  languageName = "日本語"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ja"

[en]
  title = "Game or Study Memo"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
